name: Hello World from Composite Action
on:
  push:

jobs:
  hello-world:
    name: call-consumer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Hello World
        id: hello-world
        uses: ExampleCoSoftware/jira-demo-github-composite-actions/helloworld@v1
        with:
          hello_input: "Hello ExampleCo!"
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.hello-world.outputs.random-number }}